### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by joakin** [jfecher/algorithm-j#1]
Hi!

Thank you for publishing this J implementation! It was very helpful 🙌

Would you consider adding a license to the repo?  I don’t think it has one

Have a nice day!

**Comment by jfecher** [comment]
I'm glad you found this helpful :slightly_smiling_face:  

I've licensed this project under the MIT license. It is my hope this project can be a good learning resource.

You have a nice day as well

**Comment by joakin** [comment]
Awesome thank you!
